### ISSUE TITLE
How should we handle evolving style guides?

### ISSUE THREAD

**Issue by mtchllbrrn** [poetic/poetic-meteor-style#4]
For instance, our style guide relies on & extends AirBnB's, which changes over time. Should ours change as theirs does?

**Comment by MatthewHager** [comment]
I think we should follow theirs and our styles should be on top.

**Comment by mtchllbrrn** [comment]
That would lead to a codebase's style changing throughout time. This could introduce linting errors/warnings on code that was previously clean. We would also need to think about keeping everyone up-to-date with our styles to prevent different people on a single project having different guides.

If our guide changes over time, a dev that comes onto a project at a later date will likely have a different guide than the others.

**Comment by MatthewHager** [comment]
Those are all good points. I still vote that we keep up with the present best practices and Boy Scout the code forward as concepts evolve. As for updates and versioning, whether we change it or AirBnb changes it, we should discuss this.

**Comment by Chun-Yang** [comment]
I think a style guide should NOT change and no one should even modify it. Which style guide we follow does not matter. What matters is that we have ONE style guide and everyone follows it.

I really wish we use https://github.com/feross/standard cause there is no configuration. No configuration means no argument and no update which is what a style guide should do.

What do you guys think?

**Comment by mtchllbrrn** [comment]
A few thoughts:
1. I think Standard is too limited in scope. I believe Poetic would benefit more from a style guide that is highly-opinionated. This would create a lot more learning opportunities for apprentices as their editors would helpfully point out anti-patterns in their code.
2. We can achieve a lot of the "plug and play" niceties that Standard JS offers through our implementation of Stanza. We'll need to figure out how to deal with a few things along the way (e.g. evolving style guides), but for the ground-level Poetic developer, it will be as easy as `stanza init`.
3. I personally don't like some of the Standard rules, especially their views on colons. The caveat here is that I believe personal disagreements about style are less-important than actually _having_ an enforced style guide, so this isn't a huge deal.

**Comment by Chun-Yang** [comment]
I am really glad that we are actually having this conversation.
1. How is standard limited? It handles react too.
2. I do not think 'EVOLVING' style guides is a good idea. If the language does not change, we should not change the style guide. I do not think while we follow a style guide and have to change the style over time is a good idea. Yes, we CAN achieve 'plug and play'. The thing is if we use standard, we do NOT NEED to.

**Comment by mtchllbrrn** [comment]
From what I find, Standard simply doesn't have as many rules. Check out the AirBnB JS style docs: https://github.com/airbnb/javascript

Note that this is *just* Javascript, it doesn't include all of their React stuff.

I agree with your other points, and I agree that any single rule should not be a sticking point (see [Law of Triviality](https://en.wikipedia.org/wiki/Law_of_triviality)).

**Comment by Chun-Yang** [comment]
I agree that Standard is limited in the sense that it does not have as much rules as AirBnB has. It however does include React stuff.

```
packages used by standard

eslint - AST-based pattern checker for JavaScript
standard-engine - standard's guts, extracted into a reuseable package. build your own!
eslint-config-standard - standard eslint rules, as a shareable config
eslint-config-standard-react - standard eslint rules for React and JSX
eslint-plugin-standard - standard custom eslint rules (not part of eslint core)
```

If the number of rules is a deal breaker then let's stick with AirBnB. 

The question then becomes do we need a style guide of ourself? Why do we instead just need to copy from AirBnB ?

**Comment by mtchllbrrn** [comment]
@Chun-Yang Let's just put this on the other thread. I deleted my previous comment and moved it over.
