### ISSUE TITLE
ESLint complains about alerts, but we've decided to use system dialogs

### ISSUE THREAD

**Issue by khalidadil** [poetic/poetic-meteor-style#5]
Based on the `no-alert` rule, ESLint complains about `alert`, `confirm`, and `prompt`.

We should remove this rule to allow us to use native Javascript dialogs.

http://eslint.org/docs/rules/no-alert

**Comment by MatthewHager** [comment]
This issue should be made on the stanza repo. Agreed though, we should just avoid console logging. We need alert, confirm and prompt.

**Comment by khalidadil** [comment]
Issue moved to stanza repo:
https://github.com/poetic/stanza/issues/9

**Comment by mtchllbrrn** [comment]
I don't think stanza is the right venue for this. We should try to keep the Stanza's constituents ("lines?" haha) as composable as possible. I like the idea of having separate repos for each of Stanza's areas of concern, and ESLint complaining about alerts is something that could certainly be fixed within this repo.

re-opening.

**Comment by MatthewHager** [comment]
@mtchllbrrn I'm fine with this, but we need to make Stanza pull its dotfiles from here or else we'll maintain this repo and no one will end up with the enhancements. Otherwise, we just maintain the dotfiles in stanza.

**Comment by mtchllbrrn** [comment]
I agree that stanza should refer directly to this repo.

**Comment by Chun-Yang** [comment]
This is resolved. `"no-alert": 0,`
